name: flutter_keychain
description: Flutter secure storage via Keychain (iOS) and Keystore (Android). Supports optional iOS access groups and item labels.
version: 3.0.1
homepage: https://github.com/jeroentrappers/flutter_keychain

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.appmire.flutterkeychain
        pluginClass: FlutterKeychainPlugin
      ios:
        pluginClass: FlutterKeychainPlugin
